### ISSUE TITLE
Help MEH With My Code PLz

### ISSUE THREAD

**Issue by seth886** [blushiemagic/tModLoader#413]
every time i try to build and reload mod i get this error btw i use visual studios

Expected resource not found:
    Projectiles/LazerBeamMinigun/CustomBeamWeapon
Closest guess: (Is there a spelling or folder placement error?)
    Projectiles/LazerBeamProjectile

   at Terraria.ModLoader.Mod.GetTexture(String name)
   at Terraria.ModLoader.ModLoader.GetTexture(String name)
   at Terraria.ModLoader.ModItem.AutoStaticDefaults()
   at Terraria.ModLoader.Mod.SetupContent()
   at Terraria.ModLoader.ModLoader.do_Load(Object threadContext)

**Comment by JavidPack** [comment]
https://github.com/blushiemagic/tModLoader/wiki/Basic-tModLoader-Modding-FAQ#terrariamodloadermodgettexturestring-name-error

In the future DO NOT ask here for help with modding. This issue tracker is only for actual issues. If you need help, check the wiki, faq, and the discord: discord.me/tModLoader
