### ISSUE TITLE
Items with >20 lines of text crash on mouse-over

### ISSUE THREAD

**Issue by adveres** [blushiemagic/tModLoader#436]
### Description

When you reforge an item, and give it >20 lines of text, the game crashes when you mouseover that item.  This happens, specifically (but only because it's the item i have with the most lines of text), with Cheeze's `Chaos Theory` when you get it to have the `mythical` prefix.

I confirmed in Discord #support room, and jopojelly told me to file here.

### Steps to Reproduce

1. Have Cheeze's `Chaos Theory` item.
2. Enchant it with `mythical`
3. Mouseover the item, and game should crash

### Expected behavior 

I expect the game should not crash. Although one might reasonably say 20 lines is enough text...

### Actual behavior

The game crashes with an IndexOutOfBounds Exception.

### Reproduction frequency

100% reliable if you put `mythical` on this item.

### Versions

tModLoader v0.10.1.5

### Mods

![capture](https://user-images.githubusercontent.com/775690/47956870-5c2d1100-df82-11e8-9540-7fb06e770870.PNG)
Particularly Cheeze's Content Pack v1.1.2.4. I don't think the mod matters though. I suspect *any* item with >20 lines of text would crash.

### Additional Information

Game does not crash if I reforge the item to be `masterful`, giving it exactly 20 lines of text.

![m_chaos_theory_works](https://user-images.githubusercontent.com/775690/47956847-dc06ab80-df81-11e8-8033-7eb0364c5273.PNG)

Here's the stack trace:
```
Silently Caught Exception: Index was outside the bounds of the array.   at Terraria.Main.MouseText_DrawItemTooltip(Int32 rare, Byte diff, Int32 X, Int32 Y)   at Terraria.ModLoader.ModCompile.<>c.<ActivateExceptionReporting>b__15_0(Object sender, FirstChanceExceptionEventArgs exceptionArgs)
   at Terraria.Main.MouseText_DrawItemTooltip(Int32 rare, Byte diff, Int32 X, Int32 Y)
   at Terraria.Main.MouseText(String cursorText, Int32 rare, Byte diff, Int32 hackedMouseX, Int32 hackedMouseY, Int32 hackedScreenWidth, Int32 hackedScreenHeight)
   at Terraria.Main.DrawInterface_33_MouseText()
   at Terraria.Main.<SetupDrawInterfaceLayers>b__1623_29()
   at Terraria.UI.LegacyGameInterfaceLayer.DrawSelf()
   at Terraria.UI.GameInterfaceLayer.Draw()
   at Terraria.Main.DrawInterface(GameTime gameTime)
   at Terraria.Main.do_Draw(GameTime gameTime)
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)
```

**Comment by Jofairden** [comment]
> TBH, if there's that many tooltips then you may want to take it up with the mod developer.
That's not really an argument.

Adveres, I'll see if we can look into this. Without looking at it my guess is that the tooltips is an array of size 20 or something, limiting it. We'll see what we can do _if this is a tML bug_.

**Comment by Jofairden** [comment]
I can confirm what I said earlier, as vanilla is making arrays with a max size of 20:
```cs
			string[] array = new string[num3];
			bool[] array2 = new bool[num3];
			bool[] array3 = new bool[num3];
			string[] tooltipNames = new string[num3];
```

Time to make some changes

**Comment by Jofairden** [comment]
Nope, nevermind at all. We do handle this properly. This is a bug caused  by one of the mods you're using. We handle tooltips as a List once it reaches tModLoader code, so we're not restricted by 20 lines:
![image](https://user-images.githubusercontent.com/4968151/48224521-419bd300-e39a-11e8-9315-573890721deb.png)

**Comment by adveres** [comment]
Interesting. Thank you for getting back to me. I can try and reproduce with a tiny subset of mods to see if it's just Joost or something.

Closing issue. Thanks again!

**Comment by adveres** [comment]
Cool! Thanks folks.
