### ISSUE TITLE
Crash when building frequently

### ISSUE THREAD

**Issue by wooden-utensil** [blushiemagic/tModLoader#520]
### Description
When ever you build and reload a mod the following message occasionally 
occurs:

```
The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Terraria.GameInput.PlayerInput.FixDerpedRebinds()
   at Terraria.GameInput.PlayerInput.CheckRebindingProcessKeyboard(String newKey)
   at Terraria.GameInput.PlayerInput.KeyboardInput()
   at Terraria.GameInput.PlayerInput.UpdateInput()
   at Terraria.Main.DoUpdate_HandleInput()
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)

```

Then I have to press continue then try again and it works.

### Steps to Reproduce

1. Build and reload a mod source
2. and at random times the error occurs

### Expected behavior 
No error, ever!

### Actual behavior
Error appear

### Reproduction frequency
5%?

### Versions
v0.10.1.5 tModLoader v1.3.5.2

### Mods
HERO's mod - Cheat Sheet - Shorter Respawn Time - OP Rainbow Sword

### Additional Information
The error appeared to happen when the mod was building, not when reloading.

**Comment by JavidPack** [comment]
This is fixed in the next version already.

**Comment by wooden-utensil** [comment]
Thanks! I just saw it closed in a blink of my eye, and a new notification, thanks for the 20 second responce!
