### ISSUE TITLE
TextureDisposedException still prevalent in 0.11 Beta 4

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#536]
The issue fixed with https://github.com/blushiemagic/tModLoader/commit/a8645e934723420ae3a661835fdfccc9704b88ee reportedly still an issue with 0.11 Beta 4.

Report by Itorius

![](https://cdn.discordapp.com/attachments/534215632795729922/571982735833563156/unknown.png)

**Comment by JavidPack** [comment]
More info: I can replicate by changing `"Fullscreen": false,` to true in a freshly generated config.json. It seems like it gets stuck on a white screen.

**Comment by Jofairden** [comment]
I think setting Support4K and Support8K to false fixed the problem, so it's likely an issue with the HiDef thing.

**Comment by Chicken-Bones** [comment]
full log please

**Comment by wooden-utensil** [comment]
Terraria doesn't need 4K 8K etc, it's a game with large pixels, a Terraria pixel is like 4x4 in PC pixels. The screen is big enough as <kbd>1366</kbd>&times;<kbd>768</kbd>, the user can goto `.exe` &rarr; `Properties` &rarr; `Compatibility` &rarr; `Run in smaller screen resolution`.

**Comment by Jofairden** [comment]
@wooden-utensil We appreciate your input, but you are probably missing a lot of context and details to judge this issue. (So it's kindly appreciated to not clutter our github with info that isn't useful to us)

OT: I can currently trigger the issue every other launch (for some reason) after having moved a player to cloud saves. It is accompanied with:
```
[17:03:28] [1/WARN] [tML]: Silently Caught Exception: 
System.InvalidOperationException: An unexpected error has occurred.
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset(PresentationParameters presentationParameters, GraphicsAdapter graphicsAdapter)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ChangeDevice(Boolean forceCreate)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.ApplyChanges()
   at Terraria.Main.SetDisplayMode(Int32 width, Int32 height, Boolean fullscreen) in tModLoader\Terraria\Main.cs:line 62420
   at Terraria.Main.SetResolution(Int32 width, Int32 height) in tModLoader\Terraria\Main.cs:line 62307
   at Terraria.Main.UpdateDisplaySettings() in tModLoader\Terraria\Main.cs:line 62475
   at Terraria.Main.InitTargets() in tModLoader\Terraria\Main.cs:line 54052
   at Terraria.Main.SetDisplayMode(Int32 width, Int32 height, Boolean fullscreen) in tModLoader\Terraria\Main.cs:line 62456
   at Terraria.Main.OpenSettings() in tModLoader\Terraria\Main.cs:line 3145
   at Terraria.Main.ClientInitialize() in tModLoader\Terraria\Main.cs:line 7480
   at Terraria.Main.Initialize() in tModLoader\Terraria\Main.cs:line 7455
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.LaunchGame_() in tModLoader\Terraria\Program.cs:line 265
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 239
   at Terraria.WindowsLaunch.Main(String[] args) in tModLoader\Terraria\WindowsLaunch.cs:line 72
```
Currently the game will crash when this happens with the Texture2D error, if you debug in DrawData.Draw you'll find the Texture2D is disposed somehow.

**Comment by wooden-utensil** [comment]
Check for resolutions higher than the current screen size and undo the resize. Someone can resize the window bigger than their current screen resolution in windowed mode, then switch to full screen and the game crashes of the game being too big for the screen. I think this is a vanilla bug. Anyways, I looked at the error, and it seems that it is a invalid operation from `System.InvalidOperationException`, try catching that and popping up a GUI window saying that the resolution is not supported. <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F8</kbd> would also reset the display, as `Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset` probably might. Try making the program think it's a smaller resolution that it can handle, but it knows it's dealing with a bigger resolution. I don't think resolution matters, but it does matter with this error apparently.

**Comment by Chicken-Bones** [comment]
unfortunately the same sequence of graphics reset and resize calls causes the invalid operation exception with some people and not others, even when screen size and all settings are identical. It also happens sporadically, and I suspect it's something deep within the native XNA backend. More importantly, XNA itself catches that exception, the only reason you see it in the log is because we enabled logging even for caught exceptions. XNA recovers the graphics device, but doesn't re-upload all the textures.

Our current solution is to just re-acquire the textures, which if the failure is early enough is only the background textures, but it may be that failures can happen at any stage, and a better recovery method is needed.

**Comment by Chicken-Bones** [comment]
Try this on for size https://github.com/blushiemagic/tModLoader/commit/0373a737f2df9249bcd1ca4e8a865fc1b4f08cb7

**Comment by Chicken-Bones** [comment]
Test beta6
