### ISSUE TITLE
Mod.GetFileBytes crashing (0.11 Beta 4)

### ISSUE THREAD

**Issue by JavidPack** [blushiemagic/tModLoader#537]
When a mod attempts to use GetFileBytes to get `icon.png`, an exception is thrown.

Previous versions worked, and other files seem to work fine.

```[21:04:26] [1/ERROR] [Terraria]: System.IO.IOException: File not open: C:\Users\sspaa\Documents\My Games\Terraria\ModLoader\Mods\ZLegendarys.tmod
   at Terraria.ModLoader.Core.TmodFile.GetStream(FileEntry entry, Boolean newFileStream)
   at Terraria.ModLoader.Core.TmodFile.GetBytes(FileEntry entry)
   at Terraria.ModLoader.Core.TmodFile.GetBytes(String fileName)
   at Terraria.ModLoader.Mod.GetFileBytes(String name)
   at RecipeBrowser.RecipeBrowserUI.UpdateModHoverImage(UIHoverImageButtonMod button) in RecipeBrowserUI.cs:line 304
   at RecipeBrowser.RecipeBrowserUI.ModFilterButton_OnRightClick(UIMouseEvent evt, UIElement listeningElement) in RecipeBrowserUI.cs:line 285
   at Terraria.UI.UIElement.RightClick(UIMouseEvent evt)
   at Terraria.UI.UserInterface.Update(GameTime time)
   at RecipeBrowser.Tool.UIUpdate(GameTime gameTime) in RecipeBrowser\Tool.cs:line 55
   at RecipeBrowser.RecipeBrowser.UpdateUI(GameTime gameTime) in RecipeBrowser.cs:line 166
   at Terraria.ModLoader.ModHooks.UpdateUI(GameTime gameTime)
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
```

Recipe Browser code: https://github.com/JavidPack/RecipeBrowser/blob/1372032a699d1934d222ad5f856f061c3ea41c89/RecipeBrowserUI.cs#L328

**Comment by Jofairden** [comment]
Easy replication also is with Hamstar Helpers, open the mod menu and it'll do this as well

**Comment by Chicken-Bones** [comment]
Please test https://github.com/blushiemagic/tModLoader/commit/2b9a0b8b8a96b59e043378177a15311de1e706fc

**Comment by Jofairden** [comment]
The bug is still prevalent @Chicken-Bones 
For example. when trying to compile a mod with a dependency on Cheat sheet:
```
[17:35:44] [11/WARN] [tML]: Silently Caught Exception: 
System.IO.FileNotFoundException: Could not find file 'D:\Admin\Documents\My Games\Terraria\ModLoader\Mods\CheatSheet.tmod'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Terraria.ModLoader.Core.TmodFile.Read() in tModLoader\Terraria.ModLoader.Core\TmodFile.cs:line 289
   at Terraria.ModLoader.Core.TmodFile.Open() in tModLoader\Terraria.ModLoader.Core\TmodFile.cs:line 260
   at Terraria.ModLoader.Core.ModCompile.FindReferencedMods(BuildProperties properties, Dictionary`2 mods, Boolean requireWeak) in tModLoader\Terraria.ModLoader.Core\ModCompile.cs:line 439
   at Terraria.ModLoader.Core.ModCompile.FindReferencedMods(BuildProperties properties) in tModLoader\Terraria.ModLoader.Core\ModCompile.cs:line 426
   at Terraria.ModLoader.Core.ModCompile.CompileMod(BuildingMod mod, String outputPath, List`1& refMods, Boolean xna) in tModLoader\Terraria.ModLoader.Core\ModCompile.cs:line 537
   at Terraria.ModLoader.Core.ModCompile.BuildModForPlatform(BuildingMod mod, List`1& refMods, Boolean xna) in tModLoader\Terraria.ModLoader.Core\ModCompile.cs:line 481
   at Terraria.ModLoader.Core.ModCompile.Build(BuildingMod mod) in tModLoader\Terraria.ModLoader.Core\ModCompile.cs:line 342
   at Terraria.ModLoader.Core.ModCompile.Build(String modFolder) in tModLoader\Terraria.ModLoader.Core\ModCompile.cs:line 317
   at Terraria.ModLoader.UI.UIBuildMod.<>c__DisplayClass6_0.<Build>b__0(ModCompile mc) in tModLoader\Terraria.ModLoader.UI\UIBuildMod.cs:line 44
   at Terraria.ModLoader.UI.UIBuildMod.<>c__DisplayClass8_0.<Build>b__0(Object _) in tModLoader\Terraria.ModLoader.UI\UIBuildMod.cs:line 55
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by JavidPack** [comment]
Oh right. I tested this with RecipeBrowser which accesses icon.png and it works fine.
