### ISSUE TITLE
Some TerrariaHooks IL Hooks throw errors when using them

### ISSUE THREAD

**Issue by DarkLight66** [blushiemagic/tModLoader#541]
### Description
When using `IL.Terraria.ClassName.MethodName += SomeMethod` to hook onto a method and modify it at runtime, regardless of whether `SomeMethod` does anything, some methods throw the following exception:
```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MonoMod.Utils.ReflectionHelper._ResolveReflection(MemberReference mref, Module[] modules)
   at MonoMod.Utils.DynamicMethodDefinition._GenerateEmit(MethodBase _mb, ILGenerator il)
   at MonoMod.Utils.DynamicMethodDefinition.GenerateViaDynamicMethod()
   at MonoMod.Utils.DynamicMethodDefinition.Generate(Object context)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint.UpdateILManipulated(Boolean force)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint.Modify(Delegate callback)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify(MethodBase method, Delegate callback)
   at IL.Terraria.Player.add_PlaceThing(Manipulator )
   at TestMod.TestTile.Autoload(String& name, String& texture) en TestMod\TestTile.cs:line 21
   at Terraria.ModLoader.Mod.AutoloadTile(Type type)
   at Terraria.ModLoader.Mod.Autoload()
   at Terraria.ModLoader.ModContent.<>c.<Load>b__30_0(Mod mod)
   at Terraria.ModLoader.ModContent.LoadModContent(Action`1 loadAction)
   at Terraria.ModLoader.ModContent.Load()
   at Terraria.ModLoader.ModLoader.Load()
   at Terraria.ModLoader.ModLoader.<>c.<BeginLoad>b__36_0(Object _)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

So far i've tested this inside the `Autoload` method of a `ModTile` class, and with the following methods (in various orders) `WorldeGen.CheckAlch`, `Player.SmartCursorLookup`, `WorldGen.TileFrame` and `Player.PlaceThing`, and only the last two ones have thrown the exception.

### Steps to Reproduce

1. Create a simple Mod with a simple ModTile class
2. In it's `Autoload` method, add `IL.Terraria.WorldGen.TileFrame += SomeMethod`
3. Make `SomeMethod` but don't add any code to it
4. Build and load the mod

### Expected behavior 
The game should load the mod as normal

### Actual behavior
An exception is thrown

### Reproduction frequency
Always

### Versions
tModLoader v0.11 Beta 4

### Mods
None

### Additional Information
This was first found in a test version of Thorium, then i made a simple test mod and the reproduction steps are the exact same.

**Comment by Jofairden** [comment]
Tried IL hooking into PlaceThing myself and got the following:
```[23:17:02] [8/ERROR] [tML]: An error occurred while loading Loot
The mod(s) have been automatically been disabled.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Loot.Loot.<>c.<Load>b__7_0(ILContext il) in Loot.cs:line 43
   at MonoMod.Cil.ILContext.Invoke(Manipulator manip)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint.InvokeManipulator(MethodDefinition def, Delegate cb)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint.Modify(Delegate callback)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify(MethodBase method, Delegate callback)
   at IL.Terraria.Player.add_PlaceThing(Manipulator )
   at Loot.Loot.Load() in Loot.cs:line 41
   at Terraria.ModLoader.ModContent.<>c.<Load>b__30_0(Mod mod) in tModLoader\Terraria.ModLoader\ModContent.cs:line 311
   at Terraria.ModLoader.ModContent.LoadModContent(Action`1 loadAction) in tModLoader\Terraria.ModLoader\ModContent.cs:line 355
   at Terraria.ModLoader.ModContent.Load() in tModLoader\Terraria.ModLoader\ModContent.cs:line 306
   at Terraria.ModLoader.ModLoader.Load() in tModLoader\Terraria.ModLoader\ModLoader.cs:line 117
[23:17:02] [8/INFO] [tML]: Disabling Mod: Loot```

**Comment by Jofairden** [comment]
Ok, it's most likely an issue with multi-dimensional array get for the tile array:
```
call      instance class Terraria.Tile class Terraria.Tile[0..., 0...]::Get(int32, int32)
```
We need a fix in MonoMod for this to be solved. (Upgrade Monomod)

**Comment by Jofairden** [comment]
Fixed in a88af31 by upgrading Monomod RuntimeDetours and Utils after fix.
The actual problem lied in:
`newobj    instance void string[0..., 0...]::.ctor(int32, int32)`
MonoMod did not account for 2d arrays constructors, which make use of `newobj` compared to `newarr` for 1d arrays.

**Comment by Chicken-Bones** [comment]
Yeah, I remember helping 0x0ade with something like that previously. Hadn't updated MonoMod in a while though while waiting for stable. Are we on latest now?

**Comment by Jofairden** [comment]
We're on dev/latest for RuntimeDetours and Utils now, he said nothing else needed update.
